name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install & Build
      run: yarn install && yarn build

    - name: Deploy
      uses: TencentCloudBase/cloudbase-action@v1
      with:
        secretId: ${{secrets.ACCESS_ID}}
        secretKey: ${{secrets.ACCESS_KEY}}  
        staticSrcPath: outDir
        staticDestPath: home/blog-server/outDir
